# Generated by Django 4.1.3 on 2022-11-26 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submission_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
